# Cambiar a cualquier puerto disponible (ej. 8081, 9090, etc.)
server.port=9999


# Datasource
spring.datasource.url=jdbc:sqlserver://localhost:1422;databaseName=gastos;encrypt=true;trustServerCertificate=true
spring.datasource.username=udm_admin
spring.datasource.password=Password1
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# JPA/HIBERNATE CONFIGURATION
# ===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
